[agent]
  interval = "10s"
  flush_interval = "10s"

# 1. Listen to MQTT topics published to Mosquitto
[[inputs.mqtt_consumer]]
  servers =["tcp://mosquitto:1883"]
  topics = ["sensors/#"]
  data_format = "json"

# 2. Write Metrics to InfluxDB 3 Core (Uses the V2 compatible write API)
[[outputs.influxdb_v2]]
  urls = ["http://influxdb3-core:8181"]
  token = "$INFLUX_TOKEN" # Update this once InfluxDB 3 is booted
  organization = "admin"
  bucket = "sensor_data"     # In InfluxDB 3, bucket represents your database name